/**
 * Curated catalog of S&P 500 funds and share classes in Thailand.
 * Mapped to official SEC Thailand Open Data API v2 project IDs and unit classes.
 */
export const SP_FUNDS_CATALOG = [
  { code: 'AIA-US500', amc: 'AIA IM', proj_id: 'M0472_2563', class: null, name: 'AIA Global S&P 500 Fund', type: 'SP', riskLevel: 6, status: 'Registered' },
  { code: 'ASP-S&P500-A', amc: 'Asset Plus', proj_id: 'M0257_2552', class: 'ASP-S&P500-A', name: 'Asset Plus S&P 500 Index Fund (Class A)', type: 'SP', riskLevel: 6, status: 'Registered' },
  { code: 'ASP-S&P500-SSF', amc: 'Asset Plus', proj_id: 'M0257_2552', class: 'ASP-S&P500-SSF', name: 'Asset Plus S&P 500 Index Fund (SSF)', type: 'SP', riskLevel: 6, status: 'Registered' },
  { code: 'B-USPASSIVE', amc: 'Bualuang', proj_id: 'M0552_2567', class: null, name: 'Bualuang US Passive Equity Fund', type: 'SP', riskLevel: 6, status: 'Registered' },
  { code: 'ES-US500', amc: 'Eastspring', proj_id: 'M0784_2555', class: null, name: 'Eastspring US 500 Fund', type: 'SP', riskLevel: 6, status: 'Registered' },
  { code: 'ES-US500RMF', amc: 'Eastspring', proj_id: 'M0989_2555', class: null, name: 'Eastspring US 500 Retirement Mutual Fund', type: 'SP', riskLevel: 6, status: 'Registered' },
  { code: 'K-US500X-A(A)', amc: 'KAsset', proj_id: 'M0257_2564', class: 'K-US500X-A(A)', name: 'K US500X Equity Fund (Individual Class A)', type: 'SP', riskLevel: 6, status: 'Registered' },
  { code: 'K-US500XRMF', amc: 'KAsset', proj_id: 'M0408_2567', class: null, name: 'K US500X Equity Retirement Mutual Fund', type: 'SP', riskLevel: 6, status: 'Registered' },
  { code: 'K-US500XUH', amc: 'KAsset', proj_id: 'M0789_2568', class: null, name: 'K US500X Equity Fund (Unhedged)', type: 'SP', riskLevel: 6, status: 'Registered' },
  { code: 'KFUSINDFX-A', amc: 'Krungsri', proj_id: 'M0594_2567', class: 'KFUSINDFX-A', name: 'Krungsri US Equity Index FX Fund (Class A)', type: 'SP', riskLevel: 6, status: 'Registered' },
  { code: 'KFUSINDFX-I', amc: 'Krungsri', proj_id: 'M0594_2567', class: 'KFUSINDFX-I', name: 'Krungsri US Equity Index FX Fund (Class I)', type: 'SP', riskLevel: 6, status: 'Registered' },
  { code: 'KFUSINDX-A', amc: 'Krungsri', proj_id: 'M0071_2560', class: 'KFUSINDX-A', name: 'Krungsri US Equity Index Fund (Class A)', type: 'SP', riskLevel: 6, status: 'Registered' },
  { code: 'KFUSINDX-I', amc: 'Krungsri', proj_id: 'M0071_2560', class: 'KFUSINDX-I', name: 'Krungsri US Equity Index Fund (Class I)', type: 'SP', riskLevel: 6, status: 'Registered' },
  { code: 'KKP US500-H', amc: 'KKP', proj_id: 'M0298_2567', class: 'KKP US500-H', name: 'KKP US500 Hedged Fund (Class H)', type: 'SP', riskLevel: 6, status: 'Registered' },
  { code: 'KKP US500-UH', amc: 'KKP', proj_id: 'M0301_2567', class: 'KKP US500-UH', name: 'KKP US500 Unhedged Fund (Class UH)', type: 'SP', riskLevel: 6, status: 'Registered' },
  { code: 'KKP US500-UH-E', amc: 'KKP', proj_id: 'M0301_2567', class: 'KKP US500-UH-E', name: 'KKP US500 Unhedged Fund (Class E)', type: 'SP', riskLevel: 6, status: 'Registered' },
  { code: 'KKP US500-UH-M', amc: 'KKP', proj_id: 'M0301_2567', class: 'KKP US500-UH-M', name: 'KKP US500 Unhedged Fund (Class M)', type: 'SP', riskLevel: 6, status: 'Registered' },
  { code: 'KKP US500-UH-SSF', amc: 'KKP', proj_id: 'M0301_2567', class: 'KKP US500-UH-SSF', name: 'KKP US500 Unhedged Fund (SSF)', type: 'SP', riskLevel: 6, status: 'Registered' },
  { code: 'KT-S&P500-A', amc: 'KTAM', proj_id: 'M0867_2567', class: 'KT-S&P500-A', name: 'KTAM S&P 500 Index Fund (Class A)', type: 'SP', riskLevel: 6, status: 'Registered' },
  { code: 'KT-S&P500-USD-A', amc: 'KTAM', proj_id: 'M0867_2567', class: 'KT-S&P500-USD-A', name: 'KTAM S&P 500 Index Fund (Class USD-A)', type: 'SP', riskLevel: 6, status: 'Registered' },
  { code: 'M-US500H', amc: 'MFC', proj_id: 'M0405_2567', class: null, name: 'MFC US 500 Hedged Fund', type: 'SP', riskLevel: 6, status: 'Registered' },
  { code: 'SCBRMS&P500', amc: 'SCBAM', proj_id: 'M0426_2562', class: null, name: 'SCB S&P 500 Retirement Mutual Fund', type: 'SP', riskLevel: 6, status: 'Registered' },
  { code: 'SCBS&P500', amc: 'SCBAM', proj_id: 'M0643_2555', class: 'SCBS&P500', name: 'SCB S&P 500 Index Fund (Dividend Class)', type: 'SP', riskLevel: 6, status: 'Registered' },
  { code: 'SCBS&P500(SSFA)', amc: 'SCBAM', proj_id: 'M0643_2555', class: 'SCBS&P500(SSFA)', name: 'SCB S&P 500 Index Fund (SSFA Accumulation)', type: 'SP', riskLevel: 6, status: 'Registered' },
  { code: 'SCBS&P500-SSF', amc: 'SCBAM', proj_id: 'M0643_2555', class: 'SCBS&P500-SSF', name: 'SCB S&P 500 Index Fund (SSF)', type: 'SP', riskLevel: 6, status: 'Registered' },
  { code: 'SCBS&P500A', amc: 'SCBAM', proj_id: 'M0643_2555', class: 'SCBS&P500A', name: 'SCB S&P 500 Index Fund (Class A)', type: 'SP', riskLevel: 6, status: 'Registered' },
  { code: 'SCBS&P500E', amc: 'SCBAM', proj_id: 'M0643_2555', class: 'SCBS&P500E', name: 'SCB S&P 500 Index Fund (Class E)', type: 'SP', riskLevel: 6, status: 'Registered' },
  { code: 'SCBUSDS&P500', amc: 'SCBAM', proj_id: 'M1077_2568', class: null, name: 'SCB US Dollar S&P 500 Index Fund', type: 'SP', riskLevel: 6, status: 'Registered' },
  { code: 'TISCOUS-A', amc: 'TISCO', proj_id: 'M0309_2552', class: 'TISCOUS-A', name: 'TISCO US Equity Fund (Class A)', type: 'SP', riskLevel: 6, status: 'Registered' },
  { code: 'TISCOUS-SSF', amc: 'TISCO', proj_id: 'M0309_2552', class: 'TISCOUS-SSF', name: 'TISCO US Equity Fund (SSF)', type: 'SP', riskLevel: 6, status: 'Registered' },
  { code: 'TLUS500-H', amc: 'Talis', proj_id: 'M0209_2568', class: null, name: 'Talis US 500 Hedged Fund', type: 'SP', riskLevel: 6, status: 'Registered' },
  { code: 'TLUS500-UH-A', amc: 'Talis', proj_id: 'M0140_2568', class: 'TLUS500-UH-A', name: 'Talis US 500 Unhedged Fund (Class A)', type: 'SP', riskLevel: 6, status: 'Registered' },
  { code: 'TLUS500-UH-X', amc: 'Talis', proj_id: 'M0140_2568', class: 'TLUS500-UH-X', name: 'Talis US 500 Unhedged Fund (Class X)', type: 'SP', riskLevel: 6, status: 'Registered' },
];
